// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.12.0
// source: Login.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TickoutType int32

const (
	TickoutType_TICK_OUT_TYPE_NONE TickoutType = 0
	TickoutType_ACCOUNT            TickoutType = 1 //账号顶替
	TickoutType_SERVER_SHUTDOWN    TickoutType = 2 //服务器关闭
)

// Enum value maps for TickoutType.
var (
	TickoutType_name = map[int32]string{
		0: "TICK_OUT_TYPE_NONE",
		1: "ACCOUNT",
		2: "SERVER_SHUTDOWN",
	}
	TickoutType_value = map[string]int32{
		"TICK_OUT_TYPE_NONE": 0,
		"ACCOUNT":            1,
		"SERVER_SHUTDOWN":    2,
	}
)

func (x TickoutType) Enum() *TickoutType {
	p := new(TickoutType)
	*p = x
	return p
}

func (x TickoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TickoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_Login_proto_enumTypes[0].Descriptor()
}

func (TickoutType) Type() protoreflect.EnumType {
	return &file_Login_proto_enumTypes[0]
}

func (x TickoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TickoutType.Descriptor instead.
func (TickoutType) EnumDescriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{0}
}

//登录请求
//CS_USER_LOGIN
type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`   //账号
	PassWord string `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"` //密码
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassWord() string {
	if x != nil {
		return x.PassWord
	}
	return ""
}

//登录回调
//CS_USER_LOGIN
type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode int32 `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"` //错误码 0表示没有错误
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

//*
// 踢用户下线
type UserTickout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type TickoutType `protobuf:"varint,1,opt,name=type,proto3,enum=protobuf.TickoutType" json:"type,omitempty"`
}

func (x *UserTickout) Reset() {
	*x = UserTickout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTickout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTickout) ProtoMessage() {}

func (x *UserTickout) ProtoReflect() protoreflect.Message {
	mi := &file_Login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTickout.ProtoReflect.Descriptor instead.
func (*UserTickout) Descriptor() ([]byte, []int) {
	return file_Login_proto_rawDescGZIP(), []int{2}
}

func (x *UserTickout) GetType() TickoutType {
	if x != nil {
		return x.Type
	}
	return TickoutType_TICK_OUT_TYPE_NONE
}

var File_Login_proto protoreflect.FileDescriptor

var file_Login_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x44, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x57, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x57, 0x6f, 0x72, 0x64, 0x22, 0x2d, 0x0a,
	0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x38, 0x0a, 0x0b,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x47, 0x0a, 0x0b, 0x54, 0x69, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x49, 0x43, 0x4b, 0x5f, 0x4f, 0x55,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x5f, 0x53, 0x48, 0x55, 0x54, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Login_proto_rawDescOnce sync.Once
	file_Login_proto_rawDescData = file_Login_proto_rawDesc
)

func file_Login_proto_rawDescGZIP() []byte {
	file_Login_proto_rawDescOnce.Do(func() {
		file_Login_proto_rawDescData = protoimpl.X.CompressGZIP(file_Login_proto_rawDescData)
	})
	return file_Login_proto_rawDescData
}

var file_Login_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Login_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Login_proto_goTypes = []interface{}{
	(TickoutType)(0),      // 0: protobuf.TickoutType
	(*LoginRequest)(nil),  // 1: protobuf.LoginRequest
	(*LoginResponse)(nil), // 2: protobuf.LoginResponse
	(*UserTickout)(nil),   // 3: protobuf.UserTickout
}
var file_Login_proto_depIdxs = []int32{
	0, // 0: protobuf.UserTickout.type:type_name -> protobuf.TickoutType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Login_proto_init() }
func file_Login_proto_init() {
	if File_Login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTickout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Login_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Login_proto_goTypes,
		DependencyIndexes: file_Login_proto_depIdxs,
		EnumInfos:         file_Login_proto_enumTypes,
		MessageInfos:      file_Login_proto_msgTypes,
	}.Build()
	File_Login_proto = out.File
	file_Login_proto_rawDesc = nil
	file_Login_proto_goTypes = nil
	file_Login_proto_depIdxs = nil
}
